CREATE TABLE SCHULEN (
	`KUERZEL` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	`NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	`ORT_KUERZEL` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	`ORT_NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	`LAND_KUERZEL` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	`LAND_NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	`VERSION` int(10) DEFAULT 0,
	`DATE_MODIFIED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `PK_SCHULEN`
   PRIMARY KEY USING HASH (`KUERZEL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

