// =====================================================
// Project: mk-gateway
// (c) Heike Winkelvoß
// =====================================================
package de.egladil.web.mk_gateway.domain;

/**
 * TestConstants
 */
public interface TestConstants {

	String VERSANDINFO_TEST_UUID = "VERSANDINFO_TEST_UUID";

	String VERSANDINFO_ALLE_UUID = "VERSANDINFO_ALLE_UUID";

	String VERSANDINFO_LEHRER_UUID = "VERSANDINFO_LEHRER_UUID";

	String VERSANDINFO_LEHRER__BEREITS_VERSENDET_UUID = "VERSANDINFO_LEHRER__BEREITS_VERSENDET_UUID";

	String VERSANDINFO_PRIVATVERANSTALTER_UUID = "VERSANDINFO_PRIVATVERANSTALTER_UUID";

	String NEWSLETTER_TEST_UND_ALLE_UUID = "NEWSLETTER_TEST_UND_ALLE_UUID";

	String NEWSLETTER_LEHRER_UUID = "NEWSLETTER_LEHRER_UUID";

	String NEWSLETTER_PRIVATVERANSTALTER_UUID = "NEWSLETTER_PRIVATVERANSTALTER_UUID";

	String UUID_LEHRER_1 = "UUID_LEHRER_1";

	String UUID_LEHRER_2 = "UUID_LEHRER_2";

	String UUID_LEHRER_3 = "UUID_LEHRER_3";

	String UUID_LEHRER_GESPERRT = "UUID_LEHRER_GESPERRT";

	String UUID_LEHRER_ANDERE_SCHULE = "UUID_LEHRER_ANDERE_SCHULE";

	String UUID_LEHRER_OHNE_SCHULE = "UUID_LEHRER_OHNE_SCHULE";

	String UUID_PRIVAT = "UUID_PRIVAT";

	String UUID_PRIVAT_GESPERRT = "UUID_PRIVAT_GESPERRT";

	String UUID_PRIVAT_NICHT_ANGEMELDET = "UUID_PRIVAT_NICHT_ANGEMELDET";

	String UUID_PRIVAT_MEHRERE_TEILNAHMEKURZEL = "UUID_PRIVAT_MEHRERE_TEILNAHMEKURZEL";

	String UUID_PRIVAT_KEIN_TEILNAHMEKURZEL = "UUID_PRIVAT_KEIN_TEILNAHMEKURZEL";

	String SCHULKUERZEL_1 = "SCHULKUERZEL_1";

	String SCHULKUERZEL_2 = "SCHULKUERZEL_2";

	String SCHULKUERZEL_3 = "SCHULKUERZEL_3";

	String TEILNAHMENUMMER_PRIVAT = "TEILNAHMENUMMER_PRIVAT";

	String TEILNAHMENUMMER_PRIVAT_GESPERRT = "TEILNAHMENUMMER_PRIVAT_GESPERRT";

	String TEILNAHMENUMMER_PRIVAT_NICHT_ANGEMELDET = "TEILNAHMENUMMER_PRIVAT_NICHT_ANGEMELDET";

	Integer WETTBEWERBSJAHR_AKTUELL = 2020;

	Integer WETTBEWERBSJAHR_ERFASST = 2017;

}
