ALTER TABLE `WETTBEWERBE` add `IKID` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT 'Lösungsbuchstaben Inklusion';

ALTER TABLE `WETTBEWERBE` add `EINS` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT 'Lösungsbuchstaben Inklusion';

ALTER TABLE `WETTBEWERBE` add `ZWEI` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT 'Lösungsbuchstaben Inklusion';

update WETTBEWERBE SET ZWEI = 'EDBEB-CCCAB-BADED' WHERE UUID = '2010';
update WETTBEWERBE SET ZWEI = 'CDECE-DDABD-BBAAD' WHERE UUID = '2011';
update WETTBEWERBE SET ZWEI = 'ECDBD-CBCBB-CABAD' WHERE UUID = '2012';
update WETTBEWERBE SET ZWEI = 'DBCCB-EBEEB-DCBAA' WHERE UUID = '2013';
update WETTBEWERBE SET ZWEI = 'BABCA-AADBA-CCEDB' WHERE UUID = '2014';
update WETTBEWERBE SET ZWEI = 'CDDEB-DCAAE-CBCAE' WHERE UUID = '2015';
update WETTBEWERBE SET ZWEI = 'EDDAD-ECCCC-ABABD' WHERE UUID = '2016';
update WETTBEWERBE SET ZWEI = 'EACDD-CDCCE-BACBA' WHERE UUID = '2017';
update WETTBEWERBE SET ZWEI = 'ECBAC-EBCDC-DABAA' WHERE UUID = '2018';
update WETTBEWERBE SET ZWEI = 'BAECA-CACBE-DECEC' WHERE UUID = '2019';
update WETTBEWERBE SET ZWEI = 'DBCEA-ABCED-BCBEB' WHERE UUID = '2020';

update WETTBEWERBE SET EINS = 'BABCA-AADBA-CCEDB' WHERE UUID = '2014';
update WETTBEWERBE SET EINS = 'CDDEB-DCAAE-CBCAE' WHERE UUID = '2015';
update WETTBEWERBE SET EINS = 'EDDAD-ECCCC-ABABD' WHERE UUID = '2016';
update WETTBEWERBE SET EINS = 'CDAD-ECCC-BCDE' WHERE UUID = '2017';
update WETTBEWERBE SET EINS = 'EAED-CCEB-BDBA' WHERE UUID = '2018';
update WETTBEWERBE SET EINS = 'CEBE-DDEC-BCAE' WHERE UUID = '2019';
update WETTBEWERBE SET EINS = 'EBCA-CCDB-EBAD' WHERE UUID = '2020';

update WETTBEWERBE SET IKID = 'AC-CB-BC' WHERE UUID = '2019';
update WETTBEWERBE SET IKID = 'AA-CB-BC' WHERE UUID = '2020';
