CREATE TABLE USERS (
	`UUID` varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci PRIMARY KEY COMMENT 'UUID aus authprovider',
  	`ROLE` varchar(100) CHARACTER SET utf8 NOT NULL,
	`VERSION` int(10) DEFAULT 0,
	`DATE_MODIFIED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

