DROP TABLE TEMP_LOESUNGSZETTEL;

DROP TABLE TEMP_PRIVATTEILNAHMEN;

CREATE TABLE LZ_TMP as SELECT * FROM LOESUNGSZETTEL;

DROP TABLE LOESUNGSZETTEL;

set @row_num=0;

CREATE TABLE LOESUNGSZETTEL AS SELECT (@row_num:=@row_num+1) AS SORTNR,
	UUID,
	WETTBEWERB_UUID,
	TEILNAHMEART,
	TEILNAHMENUMMER,
	KLASSENSTUFE,
	PUNKTE,
	KAENGURUSPRUNG,
	LANDKUERZEL,
	SPRACHE,
	QUELLE,
	NUTZEREINGABE,
	ANTWORTCODE,
	WERTUNGSCODE,
	TYPO,
	VERSION,
	DATE_MODIFIED,
	KIND_ID
FROM LZ_TMP
ORDER BY DATE_MODIFIED;

ALTER TABLE LOESUNGSZETTEL CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE LOESUNGSZETTEL ADD PRIMARY KEY(UUID);

ALTER TABLE LOESUNGSZETTEL ADD UNIQUE KEY `uk_loesungszettel_1` (`TEILNAHMEART`,`WETTBEWERB_UUID`,`TEILNAHMENUMMER`,`KLASSENSTUFE`,`KIND_ID`);

ALTER TABLE LOESUNGSZETTEL MODIFY SORTNR BIGINT NOT NULL;

ALTER TABLE LOESUNGSZETTEL MODIFY VERSION INT(10) NOT NULL DEFAULT 0;

ALTER TABLE LOESUNGSZETTEL ADD UNIQUE KEY `uk_loesungszettel_2` (`SORTNR`);

CREATE TABLE UPLOADS_TMP AS SELECT * FROM UPLOADS;

DROP TABLE UPLOADS;

set @row_num=0;

CREATE TABLE UPLOADS AS SELECT (@row_num:=@row_num+1) AS SORTNR,
	UUID,
	BENUTZER_UUID,
	TEILNAHMENUMMER,
	DATEINAME,
	UPLOAD_TYPE,
	CHARSET,
	STATUS,
	MEDIATYPE,
	CHECKSUMME,
	DATE_UPLOAD,
	VERSION
FROM UPLOADS_TMP
ORDER BY DATE_UPLOAD;;

ALTER TABLE UPLOADS ADD PRIMARY KEY(UUID);

ALTER TABLE UPLOADS ADD UNIQUE KEY `uk_uploads_1` (`BENUTZER_UUID`,`CHECKSUMME`,`TEILNAHMENUMMER`);

ALTER TABLE UPLOADS MODIFY SORTNR BIGINT NOT NULL;

ALTER TABLE UPLOADS MODIFY VERSION INT(10) NOT NULL DEFAULT 0;

ALTER TABLE UPLOADS ADD UNIQUE KEY `uk_uploads_2` (`SORTNR`);

ALTER TABLE UPLOADS CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE OR REPLACE VIEW VW_UPLOADS AS
SELECT u.SORTNR,
    u.UUID,
	u.BENUTZER_UUID,
	u.TEILNAHMENUMMER,
	u.UPLOAD_TYPE,
	u.STATUS,
	u.MEDIATYPE,
	u.DATE_UPLOAD,
	u.CHARSET,
	u.DATEINAME,
	t.SCHULNAME,
	t.WETTBEWERB_UUID,
	v.FULL_NAME,
	v.EMAIL
FROM UPLOADS u, TEILNAHMEN t, VERANSTALTER v
WHERE u.TEILNAHMENUMMER = t.TEILNAHMENUMMER
  AND u.BENUTZER_UUID = v.UUID
ORDER BY u.SORTNR;

DROP TABLE UPLOADS_TMP;

DROP TABLE LZ_TMP;
