CREATE TABLE SCHULKOLLEGIEN (
	`UUID` varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL PRIMARY KEY COMMENT 'schulkuerzel',
  	`KOLLEGIUM` JSON COMMENT 'Lehrer mit uuid und fullName',
	`VERSION` int(10) DEFAULT 0,
	`DATE_MODIFIED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	 CHECK (JSON_VALID(KOLLEGIUM))
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
