CREATE OR REPLACE VIEW VW_UPLOADS AS
SELECT u.SORTNR,
    u.UUID,
	u.BENUTZER_UUID,
	u.TEILNAHMENUMMER,
	u.UPLOAD_TYPE,
	u.STATUS,
	u.MEDIATYPE,
	u.DATE_UPLOAD,
	u.CHARSET,
	u.DATEINAME,
	v.FULL_NAME,
	v.EMAIL
FROM UPLOADS u, VERANSTALTER v
WHERE u.BENUTZER_UUID = v.UUID
ORDER BY u.SORTNR;
