ALTER TABLE `MUSTERTEXTE` add `KATEGORIE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Kategorie entsprechend enum MustertextKategorie';

ALTER TABLE MUSTERTEXTE add UNIQUE KEY `uk_mustertexte_1` (`KATEGORIE`,`NAME`);

create or replace VIEW VW_MUSTERTEXTE_SHORTLIST AS SELECT UUID, KATEGORIE, NAME FROM MUSTERTEXTE;
