version: "3.7"

services:

  mk-gateway:
    image: heik2718/mk-gateway
    networks:
      - mk-network
    ports:
      - 9500:9500
    environment:
      - TZ=Europe/Berlin
    restart: on-failure:3
    depends_on:
      - mk-gateway-database
    command: ["java","-jar","app.jar"]

  mk-gateway-database:
    image: heik2718/mk_gateway-mariadb
    networks:
      - mk-network
    volumes:
      - /home/heike/docker-volumes/mk_gateway-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-database -e MYSQL_USER_FILE=/run/secrets/mysql-root-pwd
      - MYSQL_DATABASE_FILE=/run/secrets/mysql-database -e MYSQL_USER_FILE=/run/secrets/mysql-database
      - MYSQL_USER_FILE=/run/secrets/mysql-database -e MYSQL_USER_FILE=/run/secrets/mysql-user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql-database -e MYSQL_USER_FILE=/run/secrets/mysql-user-pwd
      - TZ=Europe/Berlin
    restart: on-failure:3
    command: ["mysqld"]

  mk-kataloge:
    image: heik2718/mk-kataloge
    networks:
      - mk-network
    ports:
      - 9700:9700
    environment:
      - TZ=Europe/Berlin
    restart: on-failure:3
    depends_on:
      - mk-kataloge-database
    command: ["java","-jar","app.jar"]

  mk-kataloge-database:
    image: heik2718/mk_kataloge-mariadb
    networks:
      - mk-network
    volumes:
      - /home/heike/docker-volumes/mk_kataloge-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-database -e MYSQL_USER_FILE=/run/secrets/mysql-root-pwd
      - MYSQL_DATABASE_FILE=/run/secrets/mysql-database -e MYSQL_USER_FILE=/run/secrets/mysql-database
      - MYSQL_USER_FILE=/run/secrets/mysql-database -e MYSQL_USER_FILE=/run/secrets/mysql-user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql-database -e MYSQL_USER_FILE=/run/secrets/mysql-user-pwd
      - TZ=Europe/Berlin
    restart: on-failure:3
    command: ["mysqld"]

  mk-wettbewerb-admin:
    image: heik2718/mk-wettbewerb-admin
    networks:
      - mk-network
    ports:
      - 9570:9570
    environment:
      - TZ=Europe/Berlin
    restart: on-failure:3
    depends_on:
      - mk-wettbewerb-database
    command: ["java","-jar","app.jar"]

  mk-wettbewerb:
    image: heik2718/mk-wettbewerb
    networks:
      - mk-network
    ports:
      - 9550:9550
    environment:
      - TZ=Europe/Berlin
    restart: on-failure:3
    depends_on:
      - mk-wettbewerb-database
    command: ["java","-jar","app.jar"]

  mk-wettbewerb-database:
    image: heik2718/mk_wettbewerb-mariadb
    networks:
      - mk-network
    volumes:
      - /home/heike/docker-volumes/mk_wettbewerb-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-database -e MYSQL_USER_FILE=/run/secrets/mysql-root-pwd
      - MYSQL_DATABASE_FILE=/run/secrets/mysql-database -e MYSQL_USER_FILE=/run/secrets/mysql-database
      - MYSQL_USER_FILE=/run/secrets/mysql-database -e MYSQL_USER_FILE=/run/secrets/mysql-user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql-database -e MYSQL_USER_FILE=/run/secrets/mysql-user-pwd
      - TZ=Europe/Berlin
    restart: on-failure:3
    command: ["mysqld"]

networks:
   mk-network:

