== Ideensammlung

Die neue Anwendung "Minikänguru in Bildern und Zahlen" ist open data, d.h. es gibt keine Zugangshürden. Sie löst die mkod-app ab.

Optionen:

* Beteilungungsstatistik anzeigen (Anzahl Schulanmeldungen, Anzahl Privatanmeldungen, Anzahl beteiligter Kinder gesamt und nach Klassenstufen und nach Art der Teilnahme und nach Sprache)

* In der Beteiligungsstatistik Unterrubriken für einzelne Länder mit gleicher Aufschlüsselung

* Navigation zu den Aufgaben (nach Klassenstufe)

* Liste soll zunächst nur die Aufgabennummer und das Tortendiagramm r/f/n anzeigen, damit man einen ersten visuellen Eindruck bekommt

* Bei Klick auf ein Item wird das Bild der Aufgabe geladen und zusammen mit dem Tortendiagramm größer angezeigt. Das bedeutet, dass mkbiza-api die Klassenstufe des Wettbewerbs läd, auspackt, mit den r/f/n-Statistiken merged und dann zurückgibt. Der Rest kann dann komplett im Browser erfolgen. 

* Aus Trafic-Gründen ist es vielleicht ratsam, die geladenen Wettbewerbe bis zum F5 im Store zu halten.


=== Weitere Statistiken

[x] je Aufgabe: Anzahl Antworten zu jedem Antwortbuchstaben als Balkendiagramm

[x] Anzahl Kinder je Punktintervall

[x] Rohpunkte irgendwie auflisten (als Tabelle oder als gekippte Balkengrafik)

[x] Anzahl Kinder mit voller Punktzahl

[x] Passung des Schwierigkeitsgrads der Aufgabe

[x] Prozent richtiger Lösungen

== Schwellwerte für die Aufgabenkategorien

* Kategorie A: [80,100]
* Kategorie B: (20,80)
* Kategorie C: [0,20] 
