== Aufsetzen der Angular-Anwendung

Hier die Befehle zum Generieren von Dingen für das Frontend

[source,cli]
----
npx create-nx-workspace@latest mkbiza-app
----

Habe mich für ein stanalone project entschieden, weil es ein sehr überschaubares kleines Angular-Projekt ist, von dem ich keinerlei libs irgendwo verwenden werde.

=== scripts hinzugefügt

[source,json,source-file="package.json"]
----
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js",
    "start": "nx serve mkbiza-app",
    "build:mkbiza-app:local": "npx nx build mkbiza-app -c local --output-hashing=all --base-href /mkbiza-app/ --skip-nx-cache",
    "build:mkbiza-app:a300": "npx nx build mkbiza-app -c a300 --output-hashing=all --base-href /mkbiza-app/ --skip-nx-cache",
    "build:mkbiza-app:prod": "npx nx run mkbiza-app:build:production --output-hashing=all --base-href /mkbiza-app/ --skip-nx-cache",
    "test": "npx nx test",
    "test:all": "npx nx run-many --target=test --all",
    "lint:all": "npx nx run-many --target=lint --all",
    "full-check": "npx nx run-s lint:all test:all build",
    "graph": "npx nx graph"
  },

----

=== buildprofile einrichten

Im root-Verzeichnis des workspaces einen Verzeichnisbaum

----
mkbiza-ws
|-- apps
|-- build-env
    |-- mkbiza-app
        |-- environment.a300.ts
        |-- environment.local.ts
        |-- index.a300.html
        |-- index.prod.html
----

Diese Files werden in project.json verwendet, um die dev-Files zu ersetzen.

Die Profile werden im project.json der app konfiguriert: 

----
mkbiza-ws
|-- apps
    |-- mkbiza-app
        |-- src
        |-- project.json
----


[source,json,source-file="project.json"]
----
      "configurations": {
        "production": {
          "budgets": [
            {
              "type": "initial",
              "maximumWarning": "500kb",
              "maximumError": "1mb"
            },
            {
              "type": "anyComponentStyle",
              "maximumWarning": "2kb",
              "maximumError": "4kb"
            }
          ],
          "index": {
            "input": "build-env/mkbiza-app/index.prod.html",
            "output": "index.html"
          },
          "fileReplacements": [
            {
              "replace": "apps/mkbiza-app/src/environments/environment.ts",
              "with": "apps/mkbiza-app/src/environments/environment.prod.ts"
            }
          ],
          "outputHashing": "all"
        },
        "local": {
          "budgets": [
            {
              "type": "initial",
              "maximumWarning": "500kb",
              "maximumError": "1mb"
            },
            {
              "type": "anyComponentStyle",
              "maximumWarning": "2kb",
              "maximumError": "4kb"
            }
          ],
          "fileReplacements": [
            {
              "replace": "apps/mkbiza-app/src/environments/environment.ts",
              "with": "build-env/mkbiza-app/environment.local.ts"
            }
          ],
          "outputHashing": "all"
        },
        "a300": {
          "budgets": [
            {
              "type": "initial",
              "maximumWarning": "500kb",
              "maximumError": "1mb"
            },
            {
              "type": "anyComponentStyle",
              "maximumWarning": "2kb",
              "maximumError": "4kb"
            }
          ],
          "index": {
            "input": "build-env/mkbiza-app/index.a300.html",
            "output": "index.html"
          },
          "fileReplacements": [
            {
              "replace": "apps/mkbiza-app/src/environments/environment.ts",
              "with": "build-env/mkbiza-app/environment.a300.ts"
            }
          ],
          "outputHashing": "all"
        },
        "development": {
          "buildOptimizer": false,
          "optimization": false,
          "vendorChunk": true,
          "extractLicenses": false,
          "sourceMap": true,
          "namedChunks": true
        }
      }
----

=== selector prefix configuriert

Nach prefix suchen und dort app  durch das spezifischere prefix ergänzen.

=== npm-Pakete hinzugefügt

[source,cli]
----
npm i @ngrx/store @ngrx/router-store @ngrx/store-devtools ngrx-store-localstorage @ngrx/effects
npm i @ngrx/eslint-plugin -D
npm i @angular/material material-icons
npm i angular2-uuid
npm i ng2-charts
----

=== Sheriff einbinden

Kleines feines [Tutorial](https://angular-camp.de/blog/strategic-design-mit-sheriff-und-standalone/)

Sheriff ist ein tool, das ungewünschte direkte dependencies und damit zyklische Abhänigkeiten verhindert.

[source,cli]
----
npm i @softarc/sheriff-core @softarc/eslint-plugin-sheriff -D
----

Anschließend in .eslint.rc einbinden:

[source,json,source-file=".eslint.rc"]
----
{
  [...],
  "overrides": [
    [...]
    {
      "files": ["*.ts"],
      "extends": ["plugin:@softarc/sheriff/default"]
    }
  ]
}
----

Sheriff-Konfigurationsdatei sheriff.config.ts im root-Verzeichnis anlegen und mit der Kopie aus dem Tutorial füllen.

=== shared-Libs sollen in ein eigenes Unterverzeichnis

[src,cli]
----
cd src/app/domains
mkdir shared 
----

=== Material-Layout in eine layout-Lib

[src,cli]
----
npx nx generate @nx/angular:library --name=layout --directory=src/app/domains/shared/layout --projectNameAndRootFormat=as-provided --style=scss --tags=domain:shared --no-interactive --dry-run 
----

Dann theme aus mja-ws kopiert.

*Konfiguration:* in project.json:

[src,json,source-file="project.json"]
----

----

=== Seitenlayout

==== sidenav

[source,cli]
----
npx nx generate @nx/angular:component --name=sidenav --directory=src/app/domains/navigation/sidenav --nameAndDirectoryFormat=as-provided --style=scss --no-interactive 
----

==== header

[source,cli]
----
npx nx generate @nx/angular:component --name=header --directory=src/app/domains/navigation/header --nameAndDirectoryFormat=as-provided --style=scss --no-interactive 
----
