== Seiten und Navigation

=== Startseite

Die Startseite enthält im oberen Bereich Balkengrafiken mit der Anzahl der Kinder sowie den Medianen, darunter die Liste der Wettbewerbe zur Navigation in die Datails.

*Attribute eines Wettbewerbs in der Übersicht*

- jahr
- status
- anzahlKinder
- medianeJeKlassenstufe (nur für beendete Wettbewerbe sind die gefüllt)

=== Detailansicht eines Wettbewerbs

In die Detailansicht navigiert man über die URL oder einen Click aus der Übersichtsseite heraus.

*Attribute des Wettbewerbs in der Detailansicht*

- jahr
- anzahlKinderGesamt
- anzahlPrivatanmeldungen
- anzahlSchulanmeldungen
- teilnehmendeSchulenGesamt (kann man als Balkendiagramm oder Tortendiagramm zusammen mit den Anmeldungen darstellen)
- klassenstufen (daraus kann man Buttons zu den Aufgabenstatistiken bauen)
- schulenJeLand (wird ein Balkendiagramm)
- schulkinderJeLand (kann man als Balkendiagramm zusammen mit den privat teilnehmenden Kindern darstellen)
- kinderJeTeilnahmeart (Tortendiagramm)
- kinderJeKlassenstufe (Tortendiagramm)
- kinderJeSprache (Tortendiagramm)
- medianeJeKlassenstufe (kann man textuell darstellen oder zusammen mit der gesamten erreichbaren Punktzahl in Tortendiagrammen oder einem Balkendiagramm)

Im oberen Bereich befinden sich die diversen Diagramme. Die Klassenstufen werden zu Buttons, um in die Detailansicht der Klassenstufe dieses Wettbewerbs zu navigieren.

Die Anzahl der Kinder ist jeweils bekannt aus "kinderJeKlassenstufe".

=== Detailansicht einer Klassenstufe eines Wettbewerbsjahres

In diese Ansicht gelangt man über die URL oder einen Click auf einen der "Klasse"-Buttons.

Im oberen Bereich kann die Anzahl der Kinder dieser Klassenstufe angezeigt werden.

Darunter untereinander die Aufgabennummern mit Punkten und Strafpunkten und dem r/f/n-Diagramm in einer Akkordeon-Ansicht. Eventuell kann die Passung zwischen Level und Schwellwerten auch gleich visualisiert werden: hierfür ist die Anzahl r im Vergleich zur Gesamtzahl der Kinder ausreichend. Die Schwellwerte sollten ggf. aus dem backend bezogen werden können.

Den Aufgabentext kann man sich durch Aufklappen der Akkordeonlamellen anzeigen lassen. Dann wird auch der Lösungsbuchstabe angezeigt.

Das Aggregierte JSON ist ein MinikaenguruKlassenstufeDto mit eingebetteten Aufgabe-Elementen. 
