alter table DOWNLOADS modify column UUID  varchar(255) not null;
alter table DOWNLOADS modify column DATE_DOWNLOAD  datetime(6);
alter table DOWNLOADS modify column DOWNLOAD_TYPE  enum ('PRIVAT_DEUTSCH','PRIVAT_ENGLISCH','SCHULE_DEUTSCH','SCHULE_ENGLISCH');
alter table DOWNLOADS modify column VERANSTALTER_UUID  varchar(255);
alter table EVENTS modify column NAME  varchar(255);
alter table EVENTS modify column TIME_OCCURED  datetime(6);
alter table KINDER modify column UUID  varchar(255) not null;
alter table KINDER modify column KLASSE_UUID  varchar(255);
alter table KINDER modify column KLASSENSTUFE  enum ('EINS','IKID','ZWEI');
alter table KINDER modify column LANDKUERZEL  varchar(255);
alter table KINDER modify column LOESUNGSZETTEL_UUID  varchar(255);
alter table KINDER modify column NACHNAME  varchar(255);
alter table KINDER modify column SPRACHE  enum ('de','en');
alter table KINDER modify column TEILNAHMEART  enum ('PRIVAT','SCHULE');
alter table KINDER modify column teilnahmenummer  varchar(255);
alter table KINDER modify column VORNAME  varchar(255);
alter table KINDER modify column ZUSATZ  varchar(255);
alter table KLASSEN modify column UUID  varchar(255) not null;
alter table KLASSEN modify column NAME  varchar(255);
alter table KLASSEN modify column SCHULKUERZEL  varchar(255);
alter table LOESUNGSZETTEL modify column UUID  varchar(255) not null;
alter table LOESUNGSZETTEL modify column ANTWORTCODE  varchar(255);
alter table LOESUNGSZETTEL modify column QUELLE  enum ('ONLINE','UPLOAD');
alter table LOESUNGSZETTEL modify column KIND_ID  varchar(255);
alter table LOESUNGSZETTEL modify column KLASSENSTUFE  enum ('EINS','IKID','ZWEI');
alter table LOESUNGSZETTEL modify column LANDKUERZEL  varchar(255);
alter table LOESUNGSZETTEL modify column NUTZEREINGABE  varchar(255);
alter table LOESUNGSZETTEL modify column SPRACHE  enum ('de','en');
alter table LOESUNGSZETTEL modify column TEILNAHMEART  enum ('PRIVAT','SCHULE');
alter table LOESUNGSZETTEL modify column TEILNAHMENUMMER  varchar(255);
alter table LOESUNGSZETTEL modify column TYPO  bit;
alter table LOESUNGSZETTEL modify column WERTUNGSCODE  varchar(255);
alter table LOESUNGSZETTEL modify column WETTBEWERB_UUID  varchar(255);
alter table MUSTERTEXTE modify column UUID  varchar(255) not null;
alter table MUSTERTEXTE modify column KATEGORIE  enum ('MAIL','NEWSLETTER');
alter table MUSTERTEXTE modify column name  varchar(255);
alter table MUSTERTEXTE modify column text  varchar(255);
alter table NEWSLETTERS modify column UUID  varchar(255) not null;
alter table NEWSLETTERS modify column betreff  varchar(255);
alter table NEWSLETTERS modify column text  varchar(255);
alter table PACEMAKERS modify column UUID  varchar(255) not null;
alter table PACEMAKERS modify column WERT  varchar(255);
alter table SCHULKOLLEGIEN modify column UUID  varchar(255) not null;
alter table SCHULKOLLEGIEN modify column KOLLEGIUM  varchar(255);
alter table TEILNAHMEN modify column UUID  varchar(255) not null;
alter table TEILNAHMEN modify column ANGEMELDET_DURCH  varchar(255);
alter table TEILNAHMEN modify column SCHULNAME  varchar(255);
alter table TEILNAHMEN modify column TEILNAHMEART  enum ('PRIVAT','SCHULE');
alter table TEILNAHMEN modify column TEILNAHMENUMMER  varchar(255);
alter table TEILNAHMEN modify column WETTBEWERB_UUID  varchar(255);
alter table UPLOADS modify column UUID  varchar(255) not null;
alter table UPLOADS modify column BENUTZER_UUID  varchar(255);
alter table UPLOADS modify column DATEINAME  varchar(255);
alter table UPLOADS modify column CHARSET  varchar(255);
alter table UPLOADS modify column MEDIATYPE  varchar(255);
alter table UPLOADS modify column STATUS  enum ('ABGEWIESEN','DATENFEHLER','EXCEPTION','HOCHGELADEN','IMPORTIERT','LEER');
alter table UPLOADS modify column TEILNAHMENUMMER  varchar(255);
alter table UPLOADS modify column DATE_UPLOAD  datetime(6);
alter table UPLOADS modify column UPLOAD_TYPE  enum ('AUSWERTUNG','KLASSENLISTE');
alter table USERS modify column UUID  varchar(255) not null;
alter table USERS modify column ROLE  enum ('ADMIN','LEHRER','PRIVAT');
alter table VERANSTALTER modify column UUID  varchar(255) not null;
alter table VERANSTALTER modify column FULL_NAME  varchar(255);
alter table VERANSTALTER modify column NEWSLETTER  bit;
alter table VERANSTALTER modify column ROLLE  enum ('ADMIN','LEHRER','PRIVAT');
alter table VERANSTALTER modify column TEILNAHMENUMMERN  varchar(255);
alter table VERANSTALTER modify column ZUGANG_UNTERLAGEN  enum ('DEFAULT','ENTZOGEN','ERTEILT');
alter table VERSANDINFOS modify column UUID  varchar(255) not null;
alter table VERSANDINFOS modify column EMPFAENGERTYP  enum ('ALLE','LEHRER','PRIVATVERANSTALTER','TEST');
alter table VERSANDINFOS modify column NEWSLETTER_UUID  varchar(255);
alter table VERSANDINFOS modify column VERSAND_BEENDET_AM  datetime(6);
alter table VERSANDINFOS modify column VERSAND_BEGONNEN_AM  datetime(6);
alter table VERTRAEGE_ADV modify column UUID  varchar(255) not null;
alter table VERTRAEGE_ADV modify column ABGESCHLOSSEN_AM  varchar(255);
alter table VERTRAEGE_ADV modify column ABGESCHLOSSEN_DURCH  varchar(255);
alter table VERTRAEGE_ADV modify column HAUSNR  varchar(255);
alter table VERTRAEGE_ADV modify column LAENDERCODE  varchar(255);
alter table VERTRAEGE_ADV modify column ORT  varchar(255);
alter table VERTRAEGE_ADV modify column PLZ  varchar(255);
alter table VERTRAEGE_ADV modify column SCHULKUERZEL  varchar(255);
alter table VERTRAEGE_ADV modify column SCHULNAME  varchar(255);
alter table VERTRAEGE_ADV modify column STRASSE  varchar(255);
alter table VERTRAEGE_ADV modify column VERTRAG_ADV_TEXT_UUID  varchar(255) not null;
alter table VERTRAEGE_ADV_TEXTE modify column UUID  varchar(255) not null;
alter table VERTRAEGE_ADV_TEXTE modify column CHECKSUMME  varchar(255);
alter table VERTRAEGE_ADV_TEXTE modify column DATEINAME  varchar(255);
alter table VERTRAEGE_ADV_TEXTE modify column VERSIONSNUMMER  varchar(255);
alter table WETTBEWERBE modify column UUID  varchar(255) not null;
alter table WETTBEWERBE modify column FREISCHALTUNG_LEHRER  datetime(6);
alter table WETTBEWERBE modify column FREISCHALTUNG_PRIVAT  datetime(6);
alter table WETTBEWERBE modify column IKID  varchar(255);
alter table WETTBEWERBE modify column EINS  varchar(255);
alter table WETTBEWERBE modify column ZWEI  varchar(255);
alter table WETTBEWERBE modify column status  enum ('ANMELDUNG','BEENDET','DOWNLOAD_LEHRER','DOWNLOAD_PRIVAT','ERFASST');
alter table WETTBEWERBE modify column BEGINN  datetime(6);
alter table WETTBEWERBE modify column ENDE  datetime(6);
