ALTER TABLE `TEILNAHMEN` add `ANGEMELDET_DURCH` varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT 'UUID des Lehrers';

ALTER TABLE `TEILNAHMEN` MODIFY COLUMN `TEILNAHMENUMMER` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
