ALTER TABLE UPLOADS CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE OR REPLACE VIEW VW_UPLOADS AS
SELECT u.UUID,
	u.BENUTZER_UUID,
	u.TEILNAHMENUMMER,
	u.UPLOAD_TYPE,
	u.STATUS,
	u.MEDIATYPE,
	u.DATE_UPLOAD,
	u.CHARSET,
	u.DATEINAME,
	t.SCHULNAME,
	t.WETTBEWERB_UUID,
	v.FULL_NAME,
	v.EMAIL
FROM UPLOADS u, TEILNAHMEN t, VERANSTALTER v
WHERE u.TEILNAHMENUMMER = t.TEILNAHMENUMMER
  AND u.BENUTZER_UUID = v.UUID
ORDER BY u.DATE_UPLOAD;

